services:
  mysqldb:
    image: mysql:9
    hostname: mysqldb
    container_name: mysqldb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/mysql.sql:/docker-entrypoint-initdb.d/01-data.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: web1
    networks:
      - web-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: .
    container_name: anime-web-frontend
    ports:
      - "3000:3000"
    networks:
      - web-network
    restart: on-failure

  backend:
    build:
      context: ./backend/
    container_name: anime-web-backend
    ports:
      - 3001:3001
    environment:
      MYSQL_HOST: mysqldb
    networks:
      - web-network
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data:
    name: db_data

networks:
  web-network:
    name: web-network
    driver: bridge
